In [1]:
import numpy as np

In [2]:
def calc_rank(T, num_a, num_b):
    l = []
    l += list(range(0, num_a))
    l += list(range(num_a + num_b, num_a + num_b + num_a))
    l += list(range(num_a, num_a + num_b))
    l += list(range(num_a + num_b + num_a, num_a + num_b + num_a + num_b))
    TT = T.reshape([2] * (num_a * 2) + [2] * (num_b * 2))
    TT = TT.transpose(*l)
    TT = TT.reshape([2 ** (num_a * 2), 2 ** (num_b * 2)])
    _, S, _ = np.linalg.svd(TT)
    return sum(S > 1e-10)

In [3]:
# random 2x2 unitary matrix
U = np.random.rand(2, 2) + 1j * np.random.rand(2, 2)
U, _ = np.linalg.qr(U)

UU = np.kron(U, U)
print(calc_rank(UU, 1, 1))

1


In [4]:
# random 4x4 unitary matrix
U = np.random.rand(4, 4) + 1j * np.random.rand(4, 4)
U, _ = np.linalg.qr(U)

print(calc_rank(U, 1, 1))

4


In [5]:
# 3 qubits - 5 qubits
# A = 2x2x2 x 2x2x2x2x2  x  2x2x2 x 2x2x2x2x2
# Finding B, C  s.t.  A  ~~  B ⊗ C  where B = 2x2x2 x 2x2x2 and C = 2x2x2x2x2 x 2x2x2x2x2
#
# R = 2x2x2 x 2x2x2  x  2x2x2x2x2 x 2x2x2x2x2 (A transposed)
# Finding B, C  s.t.  R  ~~  B ⊗ C  where B = 2x2x2 x 2x2x2x2x2 and C = 2x2x2 x 2x2x2x2x2
# By reshaping R, we get (2^3 x 2) x (2^5 x 2) matrix
# Applying SVD to this matrix, we get the rank of R

In [6]:
n_a = 3
n_b = 5
A = np.random.rand(2**n_a, 2**n_a) + 1j * np.random.rand(2**n_a, 2**n_a)
A, _ = np.linalg.qr(A)

B = np.random.rand(2**n_b, 2**n_b) + 1j * np.random.rand(2**n_b, 2**n_b)
B, _ = np.linalg.qr(B)

In [7]:
T = np.kron(A, B)
print(calc_rank(T, 3, 5))

1


In [2]:
import numpy as np
CX = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]])
CXT = CX.reshape([2, 2, 2, 2]).transpose(0, 2, 1, 3).reshape(4, 4)
U, S, Vh = np.linalg.svd(CXT)
print(U.reshape((2, 2, 4)))
# print(S)
print(Vh.reshape((4, 2, 2)).transpose(1, 2, 0))

[[[ 1.  0.  0.  0.]
  [ 0.  0.  1.  0.]]

 [[ 0.  0.  0. -1.]
  [ 0. -1.  0.  0.]]]
[[[ 0.70710678 -0.          0.70710678  0.        ]
  [ 0.         -0.70710678  0.         -0.70710678]]

 [[ 0.         -0.70710678  0.          0.70710678]
  [ 0.70710678  0.         -0.70710678  0.        ]]]


In [18]:
a = np.array([
    [1, 2, 0, 0],
    [3, 4, 0, 0],
    [0, 0, 5, 6],
    [0, 0, 7, 8]
])

# a into 2x2x2x2 tensor
a.reshape([2, 2, 2, 2]).transpose(0, 2, 1, 3).reshape(4, 4)

array([[1, 2, 3, 4],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [5, 6, 7, 8]])

In [3]:
import numpy as np

arr = np.random.rand(6, 4)

# SVD

U, S, V = np.linalg.svd(arr)

print(U.shape, S.shape, V.shape)

(6, 6) (4,) (4, 4)
